comment: false

coverage:
  status:
    project:
      default:
        target: 70
        threshold: 100
    patch:
      default:
        target: 0
        threshold: 100

codecov:
  token: 09d26b89-f181-4d10-9a99-d8ea262d82ce
